apiVersion: v1
kind: Service
metadata:
  name: {{ include "reports-ms.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "reports-ms.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http

