spring:
  datasource:
    url: jdbc:mysql://mysql:3306/reports?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: reports_user
    password: reports_pass
  kafka:
    bootstrap-servers: kafka:9092
archive:
  db:
    base-url: http://archive-db:8080

