version: "3.9"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: reports
      MYSQL_USER: reports_user
      MYSQL_PASSWORD: reports_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  reports-ms:
    image: reports-ms:1.0.0
    depends_on:
      - mysql
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reports?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: reports_user
      SPRING_DATASOURCE_PASSWORD: reports_pass
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ARCHIVE_DB_BASE_URL: http://host.docker.internal:8081
    ports:
      - "8080:8080"

  kong:
    image: kong:3.6
    depends_on:
      - reports-ms
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_LOG_LEVEL: info
    volumes:
      - ../gateway/kong.yml:/usr/local/kong/declarative/kong.yml:ro
    ports:
      - "8000:8000"
      - "8001:8001"
