image:
  repository: reports-ms
  tag: "1.0.0"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80

env:
  SPRING_PROFILES_ACTIVE: local
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reports?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: reports_user
  SPRING_DATASOURCE_PASSWORD: reports_pass
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  ARCHIVE_DB_BASE_URL: http://archive-db:8080

